language: php

php:
    - 5.3

before_script:
    - composer self-update
    - composer install

script:
    - ./vendor/bin/phpunit

sudo: false

cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
